//Play lottery. The program prompts the user to enter a two-digit number, and
//determines whether the user wins according to the following rules:
// If the user input matches the lottery number in the exact order, the award is Rs. 10,000.
// If all digits in the user input match all digits in the lottery number, the award is Rs. 5,000.
// If one digit in the user input matches a digit in the lottery number, the award is Rs. 3,000.
//Note:
//The digits of a two-digit number may be 0. If a number is less than 10, assume the number is
//preceded by a 0 to form a two-digit number. For example, number 8 is treated as 08 and
//number 0 is treated as 00 in the program.

import java.util.Scanner;
import java.util.Random;
import java.text.DecimalFormat;
public class FifthProgram {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        Random rand = new Random();
        int guess = rand.nextInt(89) + 10;
        System.out.println("Enter the number : ");
        int n = input.nextInt();
        DecimalFormat df = new DecimalFormat("00");
        String c = df.format(n);
        System.out.println("Number generated by the system : " + guess);
        if (Integer.parseInt(c) < 100) {
            if (Integer.parseInt(c) == guess) {
                System.out.println("Hurraayyy!! You won Rs.10000");
            }
            else if ((Integer.parseInt(c) / 10 == guess % 10 && Integer.parseInt(c) % 10 == guess / 10) || (Integer.parseInt(c) / 10 == guess % 10 && Integer.parseInt(c) % 10 == guess / 10)) {
                System.out.println("Wow!! You won Rs.5000");
            }
            else if (Integer.parseInt(c) / 10 == guess / 10 || Integer.parseInt(c) % 10 == guess / 10 || Integer.parseInt(c) / 10 == guess % 10 || Integer.parseInt(c) % 10 == guess % 10) {
                System.out.println("Nice try!! You won Rs.3000");
            } else {
                System.out.println("Sorry! The numbers doesn't match");
            }
        }
        else
        {
            System.out.println("Wrong input, Enter a two digit number");
        }
    }
}
